# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCFENnxTtAPWOSV9izXY38ddN_HKHNDO
"""

import pandas as pd

data = {
    "Weather": ["Sunny", "Sunny", "Rainy", "Sunny"],
    "Temperature": ["Warm", "Warm", "Cold", "Warm"],
    "Humidity": ["Normal", "High", "High", "High"],
    "Wind": ["Strong", "Strong", "Strong", "Weak"],
    "PlayTennis": ["Yes", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
df.to_csv("training_data.csv", index=False)
print("CSV file 'training_data.csv' has been created successfully!")

def find_s_algorithm(data):
    features = data.iloc[:, :-1].values
    labels = data.iloc[:, -1].values

    hypothesis = None
    for i, label in enumerate(labels):
        if label == "Yes":
            hypothesis = features[i].copy()
            break
    if hypothesis is None:
        return "No positive examples found."

    for i, label in enumerate(labels):
        if label == "Yes":
            for j in range(len(hypothesis)):
                if hypothesis[j] != features[i][j]:
                    hypothesis[j] = '?'
    return hypothesis

data = pd.read_csv("training_data.csv")
print("Training Data:")
print(data)

final_hypothesis = find_s_algorithm(data)
print("\nFinal Hypothesis:")
print(final_hypothesis)

