# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCFENnxTtAPWOSV9izXY38ddN_HKHNDO
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
X = np.linspace(0, 10, 100)[:, np.newaxis]
y = np.sin(X).ravel() + np.random.normal(scale=0.2, size=100)

def lwr(X, y, x0, tau):
    w = np.exp(-((X - x0)**2).sum(axis=1) / (2 * tau**2))
    W = np.diag(w)
    X_b = np.hstack([np.ones_like(X), X])
    theta = np.linalg.pinv(X_b.T @ W @ X_b) @ X_b.T @ W @ y
    return np.array([1, x0]) @ theta

def predict(X, y, X_test, tau):
    return np.array([lwr(X, y, x[0], tau) for x in X_test])

tau = 0.5
y_pred = predict(X, y, X, tau)

plt.figure(figsize=(10, 6))
plt.scatter(X, y, s=10, color='blue', label="Data")
plt.plot(X, y_pred, color='red', label=f"LWR (tau={tau})")
plt.xlabel("X");
plt.ylabel("y");
plt.title("Locally Weighted Regression")
plt.legend();
plt.grid(True);
plt.show()

