# -*- coding: utf-8 -*-
"""lab8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCFENnxTtAPWOSV9izXY38ddN_HKHNDO
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report

def main():
    data = load_breast_cancer()
    X, y = data.data, data.target
    feature_names, target_names = data.feature_names, data.target_names

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    clf = DecisionTreeClassifier(random_state=42)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    print("Accuracy Score:", accuracy_score(y_test, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=target_names))

    plt.figure(figsize=(12, 8))
    plot_tree(clf, filled=True, feature_names=feature_names, class_names=target_names, rounded=True, proportion=True)
    plt.title("Decision Tree for Breast Cancer Classification")
    plt.show()

    sample = X_test[0]
    pred = clf.predict(sample.reshape(1, -1))
    print(f"\nClassified Sample: {'Benign' if pred[0] == 1 else 'Malignant'}")

if __name__ == "__main__":
    main()

